### ISSUE TITLE
Refresh to latest mach-glfw and vulkan-zig

### ISSUE THREAD

**Issue by genejo** [hexops/mach-glfw-vulkan-example#4]
Hello and thank you for your work!

Would you mind updating the linked repositories for these 2 linked libs? The example doesn't build out of the box with the referred versions.

Also minor. For mach-glfw did you intend to suggest `git clone https://github.com/hexops/mach-glfw` or `git clone --recurse-submodules https://github.com/hexops/mach-glfw` like for this one?

**Comment by slimsag** [comment]
Thanks for filing, sorry this repo has gone out of date. I'll try to get around to this in the next few weeks. If you want to give it a go yourself and send a PR, feel free to do so!

The `mach-glfw` repository doesn't need to be cloned with submodules, assuming you use `glfw.link(b, exe, .{});` then `build.zig` will [ensure submodules are cloned for you.](https://github.com/hexops/mach-glfw/blob/75b9f1b5efb62c7f6b86ea51c82a78de2c1757db/build.zig#L115-L125)

This repository, however (`mach-glfw-vulkan-example`) does need to be cloned with `--recurse-submodules`

**Comment by genejo** [comment]
Hey, thanks for the quick reply! And the explanation!

Actually I just copied the latest versions over the libs, removed git-related info and indeed got errors under that function which lit a bulb.

No rush with this at all and, indeed, let's see if I can figure out how to update them. You use your good time to do a lot of important stuff with the engine!
