### ISSUE TITLE
Possible bug w/ Vulkan device creation on macOS

### ISSUE THREAD

**Issue by rudedogg** [hexops/mach-glfw-vulkan-example#8]
https://github.com/hexops/mach-glfw-vulkan-example/blob/main/src/graphics_context.zig#L279-L280

I think maybe we want to use the `device_extensions` ArrayList contents here instead. It would only be an issue on macOS, but I think the intent is to add the `vk.extension_info.khr_portability_subset.name` extension for MoltenVK support.

But, if https://github.com/hexops/mach-glfw-vulkan-example/pull/7 worked maybe problems only manifest beyond the triangle example?

Anyway, it felt hard to notice, so I wanted to make an issue incase someone has issues w/ macOS/MoltenVK.

**Comment by slimsag** [comment]
@citruslee wonder if you have thoughts on this?
